// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEOb7ts2ClHb-qnBo5rqtoave8iDw4ims',
    appId: '1:809499546602:web:3bcc189466d1fc98a95893',
    messagingSenderId: '809499546602',
    projectId: 'ai-art-exhibition',
    authDomain: 'ai-art-exhibition.firebaseapp.com',
    storageBucket: 'ai-art-exhibition.appspot.com',
    measurementId: 'G-XVQ8RR9JVZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0zFd_bbyb0X_UadEO6_PlvVVZDR1Ujo',
    appId: '1:809499546602:ios:21b5e4bc2229eb7aa95893',
    messagingSenderId: '809499546602',
    projectId: 'ai-art-exhibition',
    storageBucket: 'ai-art-exhibition.appspot.com',
    iosClientId: '809499546602-iptm5r31t4u3ls5cpsjtcad5vrnja7pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiBackground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM0zFd_bbyb0X_UadEO6_PlvVVZDR1Ujo',
    appId: '1:809499546602:ios:21b5e4bc2229eb7aa95893',
    messagingSenderId: '809499546602',
    projectId: 'ai-art-exhibition',
    storageBucket: 'ai-art-exhibition.appspot.com',
    iosClientId: '809499546602-iptm5r31t4u3ls5cpsjtcad5vrnja7pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiBackground',
  );
}
